---
title: "Carnet_de_bord-Neural_Network"
author: "MathildeD_JeanT_MariusLT"
date: "25/02/2025"
output: html_document
---

## 03/02/25 - Initiation du Projet 
<div style="text-align: justify;">
L'idée de projet que nous avons décider de suivre lors du brain storming fut la création de réseau neuronale (ou Neural Network) informatique capable de discriminer les cas témoins des cas de patients atteints de diabète de type 1. Cependant partant de ce point beaucoup de choses sont encore à comprendre (Comment fonctionne un réseau neuronale ? Quel sont les bases sur lesquels s'appuient le machine learning ? etc..) et de choses à décider (Quel langage informatique ? Quel type de datas à l'entrée de ce réseau neuronal ?).

Nos premières intention étaient de coder en R (langage informatique que nous avons le plus étudié ), et d'utiliser soit les données d'expression géniques utiliser pour les différents projet de fil rouge, soit des données biomédical en lignes tel que les taux de glycémie etc... 

Mais avant de ce mettre au code, il nous a fallu comprendre les fondements et le fonctionnement d'un Neural Network. Pour cela, nous avons donc décider de regarder tous les memes vidéos explicatives de youtube dont vous avez le lien ci-dessous ( les vidéos que nous avons tous regarder dans la semaine suivante sont les vidéos 1 à 4). 
</div>
[Lien vers les videos](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&ab_channel=3Blue1Brown)

## Semaine du 17/02/25 - Choix du langage, des datas, et début de codage 
Cette semaine, nous avons donc tous regarder les videos.

### Choix du langage de code 

<div style="text-align: justify;">
Puis, nous avons pris la décision de coder en langage pyhton pour la création de notre Neural Network. En effet d'après nos recherche ce langage est non seulement le plus utilisé pour la création de réseau neuronaux, mais aussi le plus simple pour les débutants. Le langage R quand à lui est plus complexe mais offre de meilleures représentations. Mais au vu de notre niveau concernant les Neural Network, nous avons préféré la version plus débudante. 
</div>

### Choix et acquisition de nos datas

<div style="text-align: justify;">
Après avoir fait des recherhces quand au types de datas le plus facilement exploitable par un réseau de neurone,et réfléchis au contextez de notre projet. Nous avions conlu, dans un premier temps qu'il était préférable d'utiliser des données d'expression géniques (RNAseq ou Puce).\
Nous avons donc pensé à utiliser les données données par les prossefeurs dans le cadre du projet "fil_rouge" du semestre 1.\
Cependant, pour notre projet ces données n'étaient pas parfaite. Premièrement pour les données de RNA-seq, nous avions des lignées cellulaires saines et des à risque de diabète de type I. Or, pour entrainer un Neural Network à "diagnostiquer" le diabète de type I grace à des données d'expression génique, ainsi que pour le tester, nous avons besoin avec certitudes des diagnostiques.\
Ensuite pour les données obtenues par Puces, l'incovenient majeur était la très faible quantité de données. 

Nous avons donc décider de chercher sur des bases de données des données de RNA-seq chez des personnes atteintes de diabète de type 2, et chez des personnes saines. Or nous n'avons rien trouver d'exploitable comme données pour le diabète de type I, mais nous avons trouver un jeu de données sur le diabète de type II. 

[Lien ncbi vers nos données](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE81608)\
[Lien vers l'article](https://pubmed.ncbi.nlm.nih.gov/27667665/)

</div>

### Un peu de codage 
#### Mise en forme des datas 

<div style="text-align: justify;">
Pour etre utilsé dans un Neural Network, nos datas avaient besoin d'être selon un format, précis. Avec les gènes en colones et les échantillons en lignes. De plus, il nous a fallu rajouter une colonne (appeler "label") portant l'information malade/sain (1/0). C'est donc la première chose que nous avons faite. 
</div>

#### Création du réseau de neurones 

<div style="text-align: justify;">
Après avoir mis nos données au bon format, nous sommes donc rentrer dans le vif du sujet en codant pour le Neural Network à l'aide de recherhce.\
Nous avons ensuite diviser notre jeu de données en deux dont 80% servent au training du système et 20% à la validation de cet entrainement. Puis bien sur, nous avons tester notre réseau. Et explorer des pistes en vu d'améliorer les résultats de valisation obtenue (accuracity : 55%). 
</div>

#### Réduction du nombre de paramètres 

<div style="text-align: justify;">
Notre jeu de données contenait alors 40 000 gènes (colonnes) pour 1601 échantillons. Cependant ce grand nombre de gènes sont des données parasites pour le réseau car ne comportant pas de différences d'expression significatives entre les cas et les controlles. Pour palier à ça nous avons donc decider de ne garder que les 1000 gènes (5000 plus tard dans le projet) les plus significativement exprimé, et avons donc fait un trie des p.value obtenue par un test.t. 

Par la suite nous avons réaliser qu'un t.test n'était valable que lorsque les données suivent une distribution normale, et que dans le cas contraire il fallait plus utiliser un test de Mann-Whitney U. Nous avons donc modifier le code en ce sens. 
</div>

#### Pour résumé - le plan du code :

<div style="text-align: justify;">
Etape 1 : Allez chercher les données (Geo, projet transcriptomique patient/contrôle dans cellules du pancréas), labellisation des données (0 ou 1) : transformation du jeu de donnée pour le fit au modèle\
Réduction du nombre de features (de 40 000 gènes à 5000 pour éviter la pollution du modèle et l’overfitting) - calcul de la p value, classification croissante et récuperation.\
Etape 2 : Python : Définir le code pour la construction réseaux : utilisation de la librairy Pytorch et sklearn pour traitement des données et création du réseau de neurones de 1 couche (pcq moins de 10 000 échantillons dans notre modèl final)\
Étape 3 : Entraîner le réseau de neurones (Optimisation de la puissance disponible…)\
Etape 4: Interpréter les résultats\

</div>

## 26/02/25 - Modulations de paramètres 

<div style="text-align: justify;">
Afin d'améliorer l'efficacité de notre network, nous avons ensuite tester/ jouer sur plusieurs paramêtres. Et pour faire de bonne comparaison entre nos différents test, nous avons utiliser une "seed" fixe. Pour etre plus clair, un neural network par au début de son training systématiquement avec des poids et des biais random. Ce qui pour des test de comparaison peut poser problème. C'est pourquoi nous avons fait en sorte pour les test de toujours partir du même seed. 

 # Modifications random 
  
Modifications du nombre de gènes mit en input :\  
Avec une seule "hidden layer" dans le neural network:\
- 40 000 gènes : Accuracy : 90 %\
- 8 000 gènes : Accuracy : 87,75% ; Accuracy :taux de similitude dans les gènes clés : 0 %, Loss ok

Modifications du nombre de neurone dans la hidden layer:\
Pour 40 000 gènes et une seule hidden layer:\
- 64 neurones : Accuracy : 80.31%\
- 100 neurones : Accuracy: 79.69%\
- 150 neurones : Accuracy: 79.69%\
- 40 neurones : Accuracy: 81.88%\
Pour 1000 gènes et une seule hidden layer:\
- 64 neurones : Loss: 0.2997, Val Loss: 0.3697, Val Accuracy: 82.19%\
- 100 neurones : Loss: 0.2650, Val Loss: 0.3469, Val Accuracy: 84.38%\
- 150 neurones : Loss: 0.2175, Val Loss: 0.3189, Val Accuracy: 86.56%\
- 40 neurones : Accuracy: 77.50%\

Modifications du nombre de couches:\
- Couche 1 : 512 neurones, Couche 2 : 256 neurones, Couche 3 : 128 neurone, pour 20 000 gènes : Exemple d'overfiting avec une train Accuracy de 100%, et validation Accuracy de 90%\

NB : L'accuracy représente à quel point la prédiction du modèle est correcte. Si l'accuracy d'entraînement est très élevée (proche de 100%) mais que l'accuracy de validation est beaucoup plus basse, cela signifie que le modèle a appris trop spécifiquement les données d'entraînement et ne généralise pas bien aux nouvelles données
Pareil si la validation loss ne diminue pas progressivement ca veut dire que le modèle est surentrainer sur des données spécifique.
</div>

## 27/02/25 - Préparation de la présentation 

<div style="text-align: justify;">
Nous avons bien entendu pour finir, décider d'un plan à présenter, et créer un support visuel.
</div>
